---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    region: ap-southeast-2

  tasks: 
    - name: Create a new EC2 key
      ec2_key:
        name: demo-ec2-key
        region: "{{ region }}"
      register: ec2_key_result

    - name: Save private key
      copy: content="{{ ec2_key_result.key.private_key }}" dest="./demo-ec2-key.pem" mode=0600
      when: ec2_key_result.changed